### ISSUE TITLE
changeQuote doesn't work on newsgroups

### ISSUE THREAD

**Issue by BillH99999** [caligraf/ChangeQuote#20]
It appears that changeQuote doesn't work with newsgroups.  It is working great on my regular email accounts.

Am I missing something?  Is there a way to make it work with newsgroups?  If not,  I am requesting that as an enhancement.

Thanks!
Bill

**Comment by BillH99999** [comment]
Just bumping this since I haven't received any response.  There is a tab and field which allows an alternative definition for headers for newsgroups, but it doesn't work.  

If I specify my alternative header using this:

%D, %d %M %Y, at %h:%i %A

The header appears as this in my reply:

%'D, %'d %'M %'Y, at %'h:%'i %'A

This same definition works great in regular email accounts.  

Thanks,
Bill

**Comment by caligraf** [comment]
fixed on 1.7.9 version

**Comment by BillH99999** [comment]
Sorry @caligraf,

I was actually thinking of the problem with the extraneous " ([[br) />" at the end when following up to newsgroups.  I didn't realize I was actually replying to a different problem that I had reported back in 2021.  My mistake.

This problem still exists although  is a bit different for me now.

If I specify my alternative header using this:

%D, %d %M %Y, at %h:%i %A

The header appears as this in my reply:

%D, %d %M %Y, at %h:%i %A  (no apostrophes as there where when I originally reported it.

Still no substitution is being preformed. 

Thanks,
Bill

**Comment by caligraf** [comment]
You get this behavior because %D, %d .... %A are only applicable on customized dates.
In customized headers field for newsgroups you can only use %%1, %%2 ... %%9
if you put %%5 it will use the date format configured for reply regular emails.

**Comment by BillH99999** [comment]
@caligraf 

Oops... I see what I was doing wrong.  Thanks for the explanaion.  My mistake.

Thanks,
Bill
